# Generated by Django 6.0 on 2025-12-13 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
        ('subscribers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='status',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='owner',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='newsletters',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='recipients',
            field=models.ManyToManyField(to='subscribers.subscriber'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
