# Generated by Django 6.0 on 2025-12-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_alter_newsletter_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='owner',
            new_name='admin',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=20),
        ),
    ]
